### PR TITLE
Update pt_br.ts

### PR DESCRIPTION
**Pull request by thiagodalsoto**
For Version 3.0 Beta

### CODE REVIEW

**Comment by XMuli** [comment]
hhhhh, happy; I just updated it a few minutes ago *.ts and exe test packages

**Comment by thiagodalsoto** [comment]
Geez, did it break? I had the page open for over an hour and I sent it to
publish, maybe I published it over the top, if you want to compile it again
and send it to me I'll validate if everything is correct.

Em seg., 23 de dez. de 2024 às 10:06, Wengeng Zhang <
***@***.***> escreveu:

**Comment by XMuli** [comment]
Integrated, can re-pull pt_br.ts to update the file
update: using `nHNjR%y9U3z%7QZZVTq`     [SunnyCapturer_3.0_beta_1223.zip](https://github.com/user-attachments/files/18230242/SunnyCapturer_3.0_beta_1223.zip)

**Comment by XMuli** [comment]
Yeah, you're a fast translator. Super surprise.

**Comment by thiagodalsoto** [comment]
password invalid!

send the password again :)

**Comment by XMuli** [comment]
It's been updated. Try it again.

**Pull request merged**
